apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "adguard.fullname" . }}-pv
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/{{ include "adguard.fullname" . }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "adguard.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: ""
  volumeName: {{ include "adguard.fullname" . }}-pv
