apiVersion: v1
kind: Service
metadata:
  name: {{ include "adguard.fullname" . }}-service
spec:
  selector:
    app: {{ include "adguard.fullname" . }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.http.port }}
    targetPort: {{ .Values.service.http.targetPort }}
    name: http
  - protocol: TCP
    port: {{ .Values.service.httpInitial.port }}
    targetPort: {{ .Values.service.httpInitial.targetPort }}
    name: http-initial
  - protocol: UDP
    port: {{ .Values.service.dns.port }}
    targetPort: {{ .Values.service.dns.targetPort }}
    name: dns
  type: {{ .Values.service.type }}
  internalTrafficPolicy: Local
